### PR TITLE
updated for capsule isolation

### PR DESCRIPTION
**Pull request by Ichimonji10**
Supercedes #14.

### CODE REVIEW

**Comment by cswiii** [comment]
I will ACK for @Ichimonji10 since he submitted my PR... X-|

**Comment by Ichimonji10** [comment]
The commit in this PR was made from two separate commits in #14. This PR has been submitted because the history in <a href='/cswiii/katello-rapidnode'>cswiii/katello-rapidnode</a> and <a href='/SatelliteQE/katello-rapidnode'>SatelliteQE/katello-rapidnode</a> got a bit messed up, and an easy solution was for me to take those commits and make a new PR out of them. The more proper alternative would have been to fix the original PR, but that would have been a total PITA.

**Comment by Ichimonji10** [comment]
Looks good to me too. ACK. I think it would be good to have another set of eyes to look this over too, though.

**Comment by JacobCallahan** [comment]
ACK

**Pull request merged**
